# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$bootstrap=<<SCRIPT
apt-get update
curl -sSL https://get.docker.com/ | sudo sh
gpasswd -a vagrant docker
apt-get -y install python-dev
apt-get -y install python-pip
pip install docker-py==0.7.0
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "ansible"
  config.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "1024"] 
  end

  config.vm.provision :shell, inline: $bootstrap

  config.vm.define "a" do |a|
    a.vm.network :private_network, ip: "192.168.33.10"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "dock.yml"
    ansible.groups = {
       "nginx" => ["a"],
       "all_groups:children" => ["nginx"]
    }
    ansible.host_key_checking = "false"
    ansible.extra_vars = {ansible_ssh_user: 'vagrant'}
  end
  
end
