# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$bootstrap=<<SCRIPT
apt-get update
apt-get -y install unzip
apt-get -y install python-pip
curl -sSL https://get.docker.com/ubuntu/ | sudo sh
gpasswd -a vagrant docker
service docker restart
wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.zip
unzip google-cloud-sdk.zip
rm google-cloud-sdk.zip
google-cloud-sdk/install.sh --usage-reporting=false --path-update=true --bash-completion=true --rc-path=/home/vagrant/.bashrc --disable-installation-options
yes | /home/vagrant/google-cloud-sdk/bin/gcloud components update preview
pip install awscli
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "cloud" do |cloud|
    cloud.vm.box = "ubuntu/trusty64"
    cloud.vm.hostname = "cloud"
    cloud.vm.network :private_network, ip: "192.168.33.10"
    cloud.vm.provider "virtualbox" do |vb|
     vb.customize ["modifyvm", :id, "--memory", "1024"]
    end
    cloud.vm.provision :shell, inline: $bootstrap
  end

end
